#
#
#
#
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kazu-appss
  name: kazu-apache-php
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: kazu-app
